import React from "react";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import styles from "./../../Styles/detailedview.module.css";
import { useSelector } from "react-redux";
import Form from "react-bootstrap/Form";
function InventoryForm() {
  const shop = "Panera";
  const selectedData = useSelector((state) => state.dataReducer.selectedData);
  console.log("DATA SELECTED: ", selectedData);
  return (
    <Container
      className={`${styles[`${shop}_detailed_view_inventory_form_container`]}`}
    >
      <Form>
        <Row>
          <Col
            md={{ span: 10, offset: 1 }}
            className={`${
              styles[`${shop}_detailed_view_inventory_form_title`]
            }`}
          >
            {selectedData ? selectedData.inventory_id : "INVENTORY ID"} -{" "}
            {selectedData ? selectedData.description : "INVENTORY DESCRIPTION"}
          </Col>
        </Row>
        <Row>
          <Col md={{ span: 10, offset: 1 }}>
            <Row style={{ paddingTop: 10 }}>
              <Col
                className={`${
                  styles[`${shop}_detailed_view_inventory_form_image`]
                }`}
                md={4}
              >
                Image
              </Col>
              <Col>
                <Row
                  style={{ paddingTop: 0 }}
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={3}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    PACK
                  </Col>
                  <Col
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.pack : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={3}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    SIZE
                  </Col>
                  <Col
                    md={3}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.size : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={4}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    MEASUREMENT
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.measurement : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={3}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    UOM
                  </Col>
                  <Col
                    md={3}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.uom : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={4}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    SYSTEM PAR
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.system_par : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <div
                    className={`${
                      styles[
                        `${shop}_detailed_view_inventory_form_horizontal_line`
                      ]
                    }`}
                  ></div>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    OPEN ORDERS
                  </Col>
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.open_orders : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    ON HAND
                  </Col>
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.on_hand : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    ADJUSTED PAR
                  </Col>
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.adjusted_par : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <div
                    className={`${
                      styles[
                        `${shop}_detailed_view_inventory_form_horizontal_line`
                      ]
                    }`}
                  ></div>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    ORDER
                  </Col>
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.order_ : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    ADJUSTED ORDER
                  </Col>
                  <Col
                    md={6}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.adjusted_order : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <div
                    className={`${
                      styles[
                        `${shop}_detailed_view_inventory_form_horizontal_line`
                      ]
                    }`}
                  ></div>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    CASE
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.case_ : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    LBS
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.lb : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    BAG
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.bag : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    TRAY
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.tray : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    EA
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.ea : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    OZ
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.oz : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
                <Row
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_row`]
                  }`}
                >
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    GAL
                  </Col>
                  <Col
                    md={4}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.gal : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                  <Col
                    md={2}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_label`]
                    }`}
                  >
                    SLEEVES
                  </Col>
                  <Col
                    md={4}
                    className={`${
                      styles[`${shop}_detailed_view_inventory_form_input_col`]
                    }`}
                  >
                    <Form.Control
                      value={selectedData ? selectedData.sleeves : ""}
                      className={`${
                        styles[`${shop}_detailed_view_inventory_form_input`]
                      }`}
                    ></Form.Control>
                  </Col>
                </Row>
              </Col>
            </Row>
            <Row style={{ paddingTop: 10 }}>
              <div
                className={`${
                  styles[`${shop}_detailed_view_inventory_form_horizontal_line`]
                }`}
              ></div>
            </Row>
            <Row style={{ paddingTop: 10 }}>
              <Col
                md={4}
                className={`${
                  styles[`${shop}_detailed_view_inventory_form_label`]
                }`}
              >
                TOTAL CASES
              </Col>
              <Col
                className={`${
                  styles[`${shop}_detailed_view_inventory_form_input_col`]
                }`}
              >
                <Form.Control
                  value={""}
                  placeholder={"Calculated Total Cases"}
                  className={`${
                    styles[`${shop}_detailed_view_inventory_form_input`]
                  }`}
                ></Form.Control>
              </Col>
            </Row>
            <Row style={{ paddingTop: 10 }}>
              <div
                className={`${
                  styles[`${shop}_detailed_view_inventory_form_horizontal_line`]
                }`}
              ></div>
            </Row>
          </Col>
        </Row>
      </Form>
    </Container>
  );
}

export default InventoryForm;
